services:
    apache2:
        container_name: php
        build: php
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        env_file:
          - ./config/.env
        ports:
            - 2808:80
    db:
        container_name: db
        image: mysql
        restart: unless-stopped
        volumes:
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./config/my.cnf:/etc/mysql/my.cnf
        env_file:
          - ./config/.env
        ports:
          - 3306